modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Sunekaer/Flat-Bedrock/issues"
license="MIT License"
[[mods]]
modId="flatbedrock"
version="${file.jarVersion}"
displayName="Flat Bedrock"
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod changes the vanilia bedrock generator to make flat bedrock
'''
[[dependencies.flatbedrock]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flatbedrock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
